<?php

use Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException;
use Drupal\Component\Plugin\Exception\PluginNotFoundException;
use Drupal\Core\Entity\EntityStorageException;
use Drupal\Core\File\FileSystemInterface;
use Drupal\user\Entity\Role;

/**
 * Implements hook_install().
 * @throws EntityStorageException
 * @throws PluginNotFoundException
 * @throws InvalidPluginDefinitionException
 * @throws Exception
 */
function esn_membership_manager_install(): void
{
    /** @var FileSystemInterface $fileSystem */
    $fileSystem = Drupal::service('file_system');

    $directory = DRUPAL_ROOT . '/../../private/esn_membership_manager_storage';

    if (!$fileSystem->prepareDirectory($directory, FileSystemInterface::CREATE_DIRECTORY | FileSystemInterface::MODIFY_PERMISSIONS)) {
        Drupal::logger('esn_membership_manager')->error('Failed to create or prepare directory: @dir', ['@dir' => $directory]);
        return;
    }

    $htaccessPath = $directory . '/.htaccess';
    if (!file_exists($htaccessPath)) {
        $content = "Order deny,allow\nDeny from all\n";
        $content .= "<IfModule mod_authz_core.c>\n  Require all denied\n</IfModule>\n";
        file_put_contents($htaccessPath, $content);
    }

    $roleID = 'esn_membership_manager_admin';
    $role = Role::load($roleID);

    if (!$role) {
        $role = Role::create([
            'id' => $roleID,
            'label' => 'ESN Membership Manager Administrator',
        ]);
        $role->save();
    }

    if (empty($role->id())) {
        throw new Exception('Failed to create Role, aborting install to prevent corruption.');
    }

    $permissions = Drupal::service('user.permissions')->getPermissions();
    $modulePermissions = [];

    foreach ($permissions as $name => $definition) {
        if (isset($definition['provider']) && $definition['provider'] === 'esn_membership_manager') {
            $modulePermissions[] = $name;
        }
    }

    if (!empty($modulePermissions)) {
        user_role_grant_permissions($roleID, $modulePermissions);
    }

    $scopeStorage = Drupal::entityTypeManager()->getStorage('oauth2_scope');
    $scopeName = 'esn_scanner';
    $scope = $scopeStorage->load($scopeName);

    if (!$scope) {
        $scopeStorage->create([
            'name' => $scopeName,
            'description' => 'Grants permissions for the ESN Membership Scanner App',
            'granularity_id' => 'role',
            'granularity_configuration' => [
                'role' => $roleID
            ],
            'grant_types' => [
                'authorization_code' => ['status' => TRUE, 'description' => ''],
                'refresh_token' => ['status' => TRUE, 'description' => ''],
            ]
        ])->save();
    }

    $consumerStorage = Drupal::entityTypeManager()->getStorage('consumer');
    $clientUUID = '45534e20-5363-616e-6572-204f41757468';

    $exists = $consumerStorage->loadByProperties(['uuid' => $clientUUID]);
    if (empty($exists)) {
        $consumer = $consumerStorage->create([
            'uuid' => $clientUUID,
            'label' => 'ESN Scanner App',
            'machine_name' => 'esn_scanner_app',
            'description' => 'Authentication client for the ESN Scanner app.',
            'client_id' => $clientUUID,
            'secret' => '',
            'confidential' => FALSE,
            'third_party' => FALSE,
            'pkce' => TRUE,
            'redirect' => 'org.esncy.esnscanner://callback',
            'grant_types' => [
                'authorization_code',
                'refresh_token',
            ],
        ]);
        $consumer->save();
    }
}

/**
 * Implements hook_schema().
 */
function esn_membership_manager_schema(): array
{
    $schema['esn_membership_manager_cards'] = [
        'description' => 'Stores ESNcard numbers for distribution.',
        'fields' => [
            'id' => [
                'description' => 'Primary Key: Unique ESNcard ID.',
                'type' => 'serial',
                'unsigned' => TRUE,
                'not null' => TRUE,
            ],
            'number' => [
                'description' => 'The ESNcard number.',
                'type' => 'varchar',
                'length' => 20,
                'not null' => TRUE,
            ],
            'assigned' => [
                'description' => 'Indicates whether the card is assigned or not.',
                'type' => 'int',
                'size' => 'tiny',
                'not null' => TRUE,
                'default' => 0,
            ]
        ],
        'primary key' => ['id'],
        'unique keys' => [
            'number' => ['number'],
        ],
    ];

    $schema['esn_membership_manager_applications'] = [
        'description' => 'Stores ESN Pass and ESNcard applications.',
        'fields' => [
            'id' => [
                'description' => 'Primary Key: Unique submission ID.',
                'type' => 'serial',
                'unsigned' => TRUE,
                'not null' => TRUE,
            ],
            'name' => [
                'description' => 'First Name.',
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
            ],
            'surname' => [
                'description' => 'Surname.',
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
            ],
            'email' => [
                'description' => 'User Email.',
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
            ],
            'nationality' => [
                'description' => 'Nationality.',
                'type' => 'varchar',
                'length' => 128,
                'not null' => TRUE,
            ],
            'dob' => [
                'description' => 'Date of Birth.',
                'type' => 'varchar',
                'length' => 20,
                'not null' => TRUE,
            ],
            'mobility_status' => [
                'description' => 'The selected mobility status.',
                'type' => 'varchar',
                'length' => 128,
                'not null' => TRUE,
            ],
            'host_institution' => [
                'description' => 'Host University or Organization.',
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
            ],
            'proof_fid' => [
                'description' => 'File ID for Proof of Status.',
                'type' => 'int',
                'unsigned' => TRUE,
            ],
            'id_document_fid' => [
                'description' => 'File ID for ID Document Scan.',
                'type' => 'int',
                'unsigned' => TRUE,
            ],
            'face_photo_fid' => [
                'description' => 'File ID for Passport Style Photo.',
                'type' => 'int',
                'unsigned' => TRUE,
            ],
            'esncard' => [
                'description' => 'Was ESNcard selected.',
                'type' => 'int',
                'size' => 'tiny',
                'not null' => TRUE,
                'default' => 0,
            ],
            'pass_token' => [
                'description' => 'Unique user token for QR code.',
                'type' => 'varchar',
                'length' => 64,
            ],
            'esncard_number' => [
                'description' => 'ESNcard number.',
                'type' => 'varchar',
                'length' => 64,
            ],
            'payment_link' => [
                'description' => 'Stripe Payment link.',
                'type' => 'varchar',
                'length' => 255,
            ],
            'payment_link_id' => [
                'description' => 'Stripe Payment link ID.',
                'type' => 'varchar',
                'length' => 255,
            ],
            'approval_status' => [
                'description' => 'Current status (Pending, Paid, etc).',
                'type' => 'varchar',
                'length' => 32,
                'default' => 'Pending',
                'not null' => TRUE,
            ],
            'date_created' => [
                'description' => 'Timestamp when the submission was created.',
                'type' => 'varchar',
                'length' => 64,
                'not null' => TRUE,
            ],
            'date_approved' => [
                'description' => 'Timestamp when the submission was approved.',
                'type' => 'varchar',
                'length' => 64,
            ],
            'date_paid' => [
                'description' => 'Timestamp when payment was submitted.',
                'type' => 'varchar',
                'length' => 64,
            ],
            'date_last_scanned' => [
                'description' => 'Timestamp when the last scan was performed.',
                'type' => 'varchar',
                'length' => 64,
            ],
        ],
        'primary key' => ['id'],
        'unique keys' => [
            'pass_token' => ['pass_token'],
            'esncard_number' => ['esncard_number'],
        ],
        'indexes' => [
            'email' => ['email'],
            'approval_status' => ['approval_status']
        ],
    ];

    $schema['esn_membership_manager_authentication'] = [
        'description' => 'Stores authentication tokens for application emails.',
        'fields' => [
            'email' => [
                'description' => 'The email address requesting access.',
                'type' => 'varchar',
                'length' => 254,
                'not null' => TRUE,
            ],
            'code' => [
                'description' => 'The 8 digit verification code.',
                'type' => 'varchar',
                'length' => 8,
                'not null' => TRUE,
            ],
            'type' => [
                'description' => 'The type of authentication requested.',
                'type' => 'varchar',
                'length' => 24,
                'not null' => TRUE,
            ],
            'expires_at' => [
                'description' => 'Unix timestamp when the token expires.',
                'type' => 'int',
                'not null' => TRUE,
            ],
        ],
        'primary key' => ['email', 'type'],
        'unique keys' => [
            'unique_code' => ['code'],
        ],
    ];

    return $schema;
}